import type { EditorThemeClasses } from "lexical";

import "./PlaygroundEditorTheme.scss";

export const LEXICAL_THEME: EditorThemeClasses = {
  autocomplete: "edt-text-editor-theme__autocomplete",
  blockCursor: "edt-text-editor-theme__blockCursor",
  characterLimit: "edt-text-editor-theme__characterLimit",
  code: "edt-text-editor-theme__code",
  codeHighlight: {
    "atrule": "edt-text-editor-theme__tokenAttr",
    "attr": "edt-text-editor-theme__tokenAttr",
    "boolean": "edt-text-editor-theme__tokenProperty",
    "builtin": "edt-text-editor-theme__tokenSelector",
    "cdata": "edt-text-editor-theme__tokenComment",
    "char": "edt-text-editor-theme__tokenSelector",
    "class": "edt-text-editor-theme__tokenFunction",
    "class-name": "edt-text-editor-theme__tokenFunction",
    "comment": "edt-text-editor-theme__tokenComment",
    "constant": "edt-text-editor-theme__tokenProperty",
    "deleted": "edt-text-editor-theme__tokenDeleted",
    "doctype": "edt-text-editor-theme__tokenComment",
    "entity": "edt-text-editor-theme__tokenOperator",
    "function": "edt-text-editor-theme__tokenFunction",
    "important": "edt-text-editor-theme__tokenVariable",
    "inserted": "edt-text-editor-theme__tokenInserted",
    "keyword": "edt-text-editor-theme__tokenAttr",
    "namespace": "edt-text-editor-theme__tokenVariable",
    "number": "edt-text-editor-theme__tokenProperty",
    "operator": "edt-text-editor-theme__tokenOperator",
    "prolog": "edt-text-editor-theme__tokenComment",
    "property": "edt-text-editor-theme__tokenProperty",
    "punctuation": "edt-text-editor-theme__tokenPunctuation",
    "regex": "edt-text-editor-theme__tokenVariable",
    "selector": "edt-text-editor-theme__tokenSelector",
    "string": "edt-text-editor-theme__tokenSelector",
    "symbol": "edt-text-editor-theme__tokenProperty",
    "tag": "edt-text-editor-theme__tokenProperty",
    "unchanged": "edt-text-editor-theme__tokenUnchanged",
    "url": "edt-text-editor-theme__tokenOperator",
    "variable": "edt-text-editor-theme__tokenVariable",
  },
  embedBlock: {
    base: "edt-text-editor-theme__embedBlock",
    focus: "edt-text-editor-theme__embedBlockFocus",
  },
  hashtag: "edt-text-editor-theme__hashtag",
  heading: {
    h1: "edt-text-editor-theme__h1",
    h2: "edt-text-editor-theme__h2",
    h3: "edt-text-editor-theme__h3",
    h4: "edt-text-editor-theme__h4",
    h5: "edt-text-editor-theme__h5",
    h6: "edt-text-editor-theme__h6",
  },
  hr: "edt-text-editor-theme__hr",
  hrSelected: "edt-text-editor-theme__hrSelected",
  image: "editor-image",
  indent: "edt-text-editor-theme__indent",
  layoutContainer: "edt-text-editor-theme__layoutContainer",
  layoutItem: "edt-text-editor-theme__layoutItem",
  link: "edt-text-editor-theme__link",
  list: {
    checklist: "edt-text-editor-theme__checklist",
    listitem: "edt-text-editor-theme__listItem",
    listitemChecked: "edt-text-editor-theme__listItemChecked",
    listitemUnchecked: "edt-text-editor-theme__listItemUnchecked",
    nested: {
      listitem: "edt-text-editor-theme__nestedListItem",
    },
    olDepth: [
      "edt-text-editor-theme__ol1",
      "edt-text-editor-theme__ol2",
      "edt-text-editor-theme__ol3",
      "edt-text-editor-theme__ol4",
      "edt-text-editor-theme__ol5",
    ],
    ul: "edt-text-editor-theme__ul",
  },
  mark: "edt-text-editor-theme__mark",
  markOverlap: "edt-text-editor-theme__markOverlap",
  paragraph: "edt-text-editor-theme__paragraph",
  quote: "edt-text-editor-theme__quote",
  specialText: "edt-text-editor-theme__specialText",
  tab: "edt-text-editor-theme__tabNode",
  table: "edt-text-editor-theme__table",
  tableAddColumns: "edt-text-editor-theme__tableAddColumns",
  tableAddRows: "edt-text-editor-theme__tableAddRows",
  tableAlignment: {
    center: "edt-text-editor-theme__tableAlignmentCenter",
    right: "edt-text-editor-theme__tableAlignmentRight",
  },
  tableCell: "edt-text-editor-theme__tableCell",
  tableCellActionButton: "edt-text-editor-theme__tableCellActionButton",
  tableCellActionButtonContainer:
    "edt-text-editor-theme__tableCellActionButtonContainer",
  tableCellHeader: "edt-text-editor-theme__tableCellHeader",
  tableCellResizer: "edt-text-editor-theme__tableCellResizer",
  tableCellSelected: "edt-text-editor-theme__tableCellSelected",
  tableFrozenColumn: "edt-text-editor-theme__tableFrozenColumn",
  tableFrozenRow: "edt-text-editor-theme__tableFrozenRow",
  tableRowStriping: "edt-text-editor-theme__tableRowStriping",
  tableScrollableWrapper: "edt-text-editor-theme__tableScrollableWrapper",
  tableSelected: "edt-text-editor-theme__tableSelected",
  tableSelection: "edt-text-editor-theme__tableSelection",
  text: {
    bold: "edt-text-editor-theme__textBold",
    capitalize: "edt-text-editor-theme__textCapitalize",
    code: "edt-text-editor-theme__textCode",
    highlight: "edt-text-editor-theme__textHighlight",
    italic: "edt-text-editor-theme__textItalic",
    lowercase: "edt-text-editor-theme__textLowercase",
    strikethrough: "edt-text-editor-theme__textStrikethrough",
    subscript: "edt-text-editor-theme__textSubscript",
    superscript: "edt-text-editor-theme__textSuperscript",
    underline: "edt-text-editor-theme__textUnderline",
    underlineStrikethrough: "edt-text-editor-theme__textUnderlineStrikethrough",
    uppercase: "edt-text-editor-theme__textUppercase",
  },
};
